Diplom/Controllers/CreditController.cs
using Diplom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace Diplom.Controllers
{
    public class CreditController : Controller
    {
        DiplomEntities1 db = new DiplomEntities1();
        [HttpGet]
        public ActionResult CreditCPU(int idval)
        {
            List < ViewModel > result = new List<ViewModel>();
            if (idval!=0)
            {

                result.Add(new ViewModel { id = 1, uniqId = idval ,
                    Name = db.Cpus.FirstOrDefault(x => x.id == idval).nameCpu,
                    core = db.Cpus.FirstOrDefault(x => x.id == idval).coresCpu.GetValueOrDefault(),
                    price = db.Cpus.FirstOrDefault(x => x.id == idval).Price,
                    count = db.Cpus.FirstOrDefault(x => x.id == idval).Count.GetValueOrDefault(),
                    idbrand = db.Cpus.FirstOrDefault(x => x.id == idval).idManufacture.GetValueOrDefault(),
                    idsocket = db.Cpus.FirstOrDefault(x => x.id == idval).socketCpu.GetValueOrDefault()
                });
            }
            else
            {
                result.Add(new ViewModel { id = 1, uniqId = idval, Name = null, core = 0, price = 0, count = 0 });
            }

            foreach (var data in db.Manufacturers)
            {
                result.Add(new ViewModel { brand = data.Manufacture, id = data.id });
            }

            foreach (var data in db.Sockets)
            {
                result.Add(new ViewModel { socket = data.socket, id = data.id });

            }
            return PartialView(result);
        }

        [HttpPost]
        public void CreditCPU(FormCollection frm)
        {
            int idcpu = Convert.ToInt32(frm.Get("idCpu"));
            int idM = Convert.ToInt32(frm.Get("idManufacture"));
            int idS = Convert.ToInt32(frm.Get("socketid"));
            int core = Convert.ToInt32(frm.Get("cores"));
            decimal? price = Convert.ToDecimal(frm.Get("price"));
            int count = Convert.ToInt32(frm.Get("count"));
            if (idcpu == 0)
            {
                for (int i = 1; i < 999999; i++)
                {
                    if (!(db.Cpus.Any(x => x.id == i)))
                    {
                        idcpu = i;
                        break;
                    }
                }
                Cpus cpu = new Cpus();
                cpu.id = idcpu;
                cpu.nameCpu = frm.Get("nameCpu");
                cpu.coresCpu = core;
                cpu.Price = price;
                cpu.Count = count;
                cpu.idManufacture = idM;
                cpu.socketCpu = idS;
                db.Cpus.Add(cpu);
            }
            else
            {
                db.Cpus.FirstOrDefault(x => x.id == idcpu).nameCpu = frm.Get("nameCpu");
                db.Cpus.FirstOrDefault(x => x.id == idcpu).coresCpu = core;
                db.Cpus.FirstOrDefault(x => x.id == idcpu).Price = price;
                db.Cpus.FirstOrDefault(x => x.id == idcpu).Count = count;
                db.Cpus.FirstOrDefault(x => x.id == idcpu).idManufacture = idM;
                db.Cpus.FirstOrDefault(x => x.id == idcpu).socketCpu = idS;
            }
            db.SaveChanges();
        }

        [HttpGet]
        public ActionResult CreditMB(int idval)
        {
            List<ViewModel> result = new List<ViewModel>();
            if (idval != 0)
            {

                result.Add(new ViewModel
                {
                    id = 1,
                    uniqId = idval,
                    Name = db.MotherBoards.FirstOrDefault(x => x.id == idval).nameMB,
                    idtype = db.MotherBoards.FirstOrDefault(x => x.id == idval).RamType.id,
                    price = db.MotherBoards.FirstOrDefault(x => x.id == idval).Price,
                    count = db.MotherBoards.FirstOrDefault(x => x.id == idval).Count.GetValueOrDefault(),
                    idother = db.MotherBoards.FirstOrDefault(x=> x.id == idval).FormFactorMB.id,
                    idbus = db.MotherBoards.FirstOrDefault(x=> x.id == idval).slotBus.id,
                    idbrand = db.MotherBoards.FirstOrDefault(x => x.id == idval).idManufacture.GetValueOrDefault(),
                    idsocket = db.MotherBoards.FirstOrDefault(x => x.id == idval).Sockets.id
                });
            }
            else
            {
                result.Add(new ViewModel { id = 1, uniqId = idval });
            }

            foreach (var data in db.Manufacturers)
            {
                result.Add(new ViewModel { brand = data.Manufacture, id = data.id });
            }

            foreach (var data in db.Sockets)
            {
                result.Add(new ViewModel { socket = data.socket, id = data.id });

            }
            foreach (var data in db.slotBus)
            {
                result.Add(new ViewModel { bus = data.typeBus, id = data.id });
            }
            foreach(var data in db.RamType)
            {
                result.Add(new ViewModel { type = data.typeMemory, id = data.id });
            }
            foreach (var data in db.FormFactorMB)
            {
                result.Add(new ViewModel { other=data.nameFF, id = data.id });
            }
            return PartialView(result);
        }


        [HttpPost]
        public void CreditMB(FormCollection frm)
        {
            int idMB = Convert.ToInt32(frm.Get("idMB"));
            int idM = Convert.ToInt32(frm.Get("idManufacture"));
            int idS = Convert.ToInt32(frm.Get("socketid"));
            int idR = Convert.ToInt32(frm.Get("idRam"));
            int idF = Convert.ToInt32(frm.Get("idFF"));
            int idB = Convert.ToInt32(frm.Get("idBus")); 
            decimal? price = Convert.ToDecimal(frm.Get("price"));
            int count = Convert.ToInt32(frm.Get("count"));
            if (idMB == 0)
            {
                for (int i = 1; i < 999999; i++)
                {
                    if (!(db.MotherBoards.Any(x => x.id == i)))
                    {
                        idMB = i;
                        break;
                    }
                }
                MotherBoards MB = new MotherBoards();
                MB.id = idMB;
                MB.nameMB = frm.Get("nameMB");
                MB.FFMB = idF;
                MB.typeRam = idR;
                MB.slotsBus = idB;
                MB.idManufacture = idM;
                MB.socketMB = idS;
                MB.Price = price;
                MB.Count = count;
                db.MotherBoards.Add(MB);
            }
            else
            {
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).nameMB = frm.Get("nameMB");
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).FFMB = idF;
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).typeRam = idR;
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).slotsBus = idB;
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).Price = price;
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).Count = count;
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).idManufacture = idM;
                db.MotherBoards.FirstOrDefault(x => x.id == idMB).socketMB = idS;
            }
            db.SaveChanges();
        }

        [HttpGet]
        public ActionResult CreditRAM(int idval)
        {
            List<ViewModel> result = new List<ViewModel>();
            if (idval != 0)
            {

                result.Add(new ViewModel
                {
                    id = 1,
                    uniqId = idval,
                    Name = db.Rams.FirstOrDefault(x => x.id == idval).nameRam,
                    idFreq = db.Rams.FirstOrDefault(x => x.id == idval).typeRam.GetValueOrDefault(),
                    idtype = db.Rams.FirstOrDefault(x => x.id == idval).RamType.id,
                    price = db.Rams.FirstOrDefault(x => x.id == idval).Price,
                    count = db.Rams.FirstOrDefault(x => x.id == idval).Count.GetValueOrDefault(),
                    idbrand = db.Rams.FirstOrDefault(x => x.id == idval).idManufacture.GetValueOrDefault(),
                    cap = db.Rams.FirstOrDefault(x => x.id == idval).capRam.GetValueOrDefault()
                });
            }
            else
            {
                result.Add(new ViewModel { id = 1, uniqId = idval });
            }

            foreach (var data in db.RamType)
            {
                result.Add(new ViewModel { type = data.typeMemory, id = data.id });
            }

            foreach (var data in db.partsFreq)
            {
                result.Add(new ViewModel { frequency = data.frequency , id = data.id });

            }
            foreach (var data in db.Manufacturers)
            {
                result.Add(new ViewModel { brand = data.Manufacture, id = data.id });
            }
            return PartialView(result);
        }

        [HttpPost]
        public void CreditRAM(FormCollection frm)
        {
            int idRam = Convert.ToInt32(frm.Get("idRAM"));
            int idM = Convert.ToInt32(frm.Get("idManufacture"));
            int idR = Convert.ToInt32(frm.Get("idRamType"));
            int idF = Convert.ToInt32(frm.Get("idFreq"));
            decimal? price = Convert.ToDecimal(frm.Get("price"));
            int count = Convert.ToInt32(frm.Get("count"));
            int cap = Convert.ToInt32(frm.Get("cap"));
            if (idRam == 0)
            {
                for (int i = 1; i < 999999; i++)
                {
                    if (!(db.Rams.Any(x => x.id == i)))
                    {
                        idRam = i;
                        break;
                    }
                }
                Rams ram = new Rams();
                ram.id = idRam;
                ram.nameRam = frm.Get("nameRam");

Diplom/Views/Credit/CreditAudio.cshtml
@model List<Diplom.Models.ViewModel>


@{
    ViewBag.Title = "Запрос - Аудиокарта";
}

    @using (Ajax.BeginForm("CreditAudio", "Credit", new AjaxOptions() { HttpMethod = "POST" }))
    {
        <form>
            <section style="margin-top:30px">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1>Введите данные (Аудиокарта)</h1>
                    </div>
                    @if (Model.FirstOrDefault(x => x.id == 1).uniqId != 0)
                    {
                        <input class="form-control invisible" name="idAudio" value="@Model.FirstOrDefault(x => x.id == 1).uniqId" />
                    }
                    <div class="modal-body">
                        <table class="table table-condensed table-striped table-bordered">
                            <tr>
                                <td>Наименование:</td>
                                <td><input name="nameAudio" type="text" id="nameAudio" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).Name"></td>
                            </tr>
                            <tr>
                                <td>Производитель:</td>
                                <td>
                                    <select name="idManufacture" id="idManufacture" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.brand != null)
                                            {
                                                <option value="@item.id">@item.brand</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Шина:</td>
                                <td>
                                    <select name="idBus" id="idBus" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.bus != null)
                                            {
                                                <option value="@item.id">@item.bus</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Стоимость</td>
                                <td><input type="text" name="price" id="price" class="form-control" value="@Decimal.Round(Model.FirstOrDefault(x => x.id==1).price.GetValueOrDefault(),2)"></td>
                            </tr>
                            <tr>
                                <td>Количество:</td>
                                <td><input type="text" name="count" id="count" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).count"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button class="btn btn-primary" type="submit" onclick="sendPost('Audio')">Сохранить</button>
                    </div>
                </div>
            </section>
        </form>
    }

<script>
    $(document).ready(function () {
        $("#idManufacture").val(@Model.FirstOrDefault(x => x.id == 1).idbrand);
        $("#idBus").val(@Model.FirstOrDefault(x => x.id == 1).idbus);
    });
</script>

Diplom/Views/Credit/CreditBox.cshtml
@model List<Diplom.Models.ViewModel>


@{
    ViewBag.Title = "Запрос - Корпус";
}

    @using (Ajax.BeginForm("CreditBox", "Credit", new AjaxOptions() { HttpMethod = "POST" }))
    {
        <form>
            <section style="margin-top:30px">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1>Введите данные (Корпус)</h1>
                    </div>
                    @if (Model.FirstOrDefault(x => x.id == 1).uniqId != 0)
                    {
                        <input class="form-control invisible" name="idBox" value="@Model.FirstOrDefault(x => x.id == 1).uniqId" />
                    }
                    <div class="modal-body">
                        <table class="table table-condensed table-striped table-bordered">
                            <tr>
                                <td>Наименование:</td>
                                <td><input name="nameBox" type="text" id="nameBox" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).Name"></td>
                            </tr>
                            <tr>
                                <td>Производитель:</td>
                                <td>
                                    <select name="idManufacture" id="idManufacture" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.brand != null)
                                            {
                                                <option value="@item.id">@item.brand</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Форм-фактор:</td>
                                <td>
                                    <select name="idFF" id="idFF" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.type != null)
                                            {
                                                <option value="@item.id" id="@item.id">@item.type</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Блок питания:</td>
                                <td>
                                    <select name="idPower" id="idPower" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.Power != null)
                                            {
                                                <option value="@item.id">@item.Power (@item.cap watts)</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Стоимость</td>
                                <td><input type="text" name="price" id="price" class="form-control" value="@Decimal.Round(Model.FirstOrDefault(x => x.id==1).price.GetValueOrDefault(),2)"></td>
                            </tr>
                            <tr>
                                <td>Количество:</td>
                                <td><input type="text" name="count" id="count" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).count"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button class="btn btn-primary" type="submit" onclick="sendPost('Box')">Сохранить</button>
                    </div>
                </div>
            </section>
        </form>
    }

<script>
    $(document).ready(function () {
        $("#idManufacture").val(@Model.FirstOrDefault(x => x.id == 1).idbrand);
        $("#idPower").val(@Model.FirstOrDefault(x => x.id == 1).idPower);
        $("#idFF").val(@Model.FirstOrDefault(x => x.id == 1).idtype);
    });
</script>

Diplom/Views/Credit/CreditCPU.cshtml
@model List<Diplom.Models.ViewModel>


@{
    ViewBag.Title = "Запрос - процессор";
}

    @using (Ajax.BeginForm("CreditCPU", "Credit", new AjaxOptions() { HttpMethod = "POST" }))
    {
        <form>
            <section style="margin-top:30px">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1>Введите данные (Процессор)</h1>
                    </div>
                    @if (Model.FirstOrDefault(x => x.id == 1).uniqId != 0)
                    {
                        <input class="form-control invisible" name="idCpu" value="@Model.FirstOrDefault(x => x.id == 1).uniqId" />
                    }
                    <div class="modal-body">
                        <table class="table table-condensed table-striped table-bordered">
                            <tr>
                                <td>Наименование:</td>
                                <td><input name="nameCpu" type="text" id="nameCpu" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).Name"></td>
                            </tr>
                            <tr>
                                <td>Разьем:</td>
                                <td>
                                    <select name="socketid" id="socketid" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.socket != null)
                                            {
                                                <option value="@item.id" id="@item.id">@item.socket</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Ядер,шт:</td>
                                <td><input type="text" name="cores" id="cores" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).core"></td>
                            </tr>
                            <tr>
                                <td>Стоимость</td>
                                <td><input type="text" name="price" id="price" class="form-control" value="@Decimal.Round(Model.FirstOrDefault(x => x.id==1).price.GetValueOrDefault(),2)"></td>
                            </tr>
                            <tr>
                                <td>Количество:</td>
                                <td><input type="text" name="count" id="count" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).count"></td>
                            </tr>
                            <tr>
                                <td>Производитель:</td>
                                <td>
                                    <select name="idManufacture" id="idManufacture" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.brand != null)
                                            {
                                                <option value="@item.id">@item.brand</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button class="btn btn-primary cpuform" type="submit" onclick="sendPost('CPU')">Сохранить</button>
                    </div>
                </div>
            </section>
        </form>
    }

<script>
    $(document).ready(function () {
        $("#socketid").val(@Model.FirstOrDefault(x => x.id == 1).idsocket);
        $("#idManufacture").val(@Model.FirstOrDefault(x => x.id == 1).idbrand);
    });
</script>

Diplom/Views/Credit/CreditHDD.cshtml
@model List<Diplom.Models.ViewModel>


@{
    ViewBag.Title = "Запрос - Жесткий диск";
}

    @using (Ajax.BeginForm("CreditHDD", "Credit", new AjaxOptions() { HttpMethod = "POST" }))
    {
        <form>
            <section style="margin-top:30px">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1>Введите данные (Жесткий диск)</h1>
                    </div>
                    @if (Model.FirstOrDefault(x => x.id == 1).uniqId != 0)
                    {
                        <input class="form-control invisible" name="idHDD" value="@Model.FirstOrDefault(x => x.id == 1).uniqId" />
                    }
                    <div class="modal-body">
                        <table class="table table-condensed table-striped table-bordered">
                            <tr>
                                <td>Наименование:</td>
                                <td><input name="nameHDD" type="text" id="nameHDD" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).Name"></td>
                            </tr>
                            <tr>
                                <td>Производитель:</td>
                                <td>
                                    <select name="idManufacture" id="idManufacture" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.brand != null)
                                            {
                                                <option value="@item.id">@item.brand</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Тип памяти:</td>
                                <td>
                                    <select name="idRam" id="idRam" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.type != null)
                                            {
                                                <option value="@item.id">@item.type</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Вместимость: </td>
                                <td><input type="text" name="cap" id="cap" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).cap"></td>
                            </tr>
                            <tr>
                                <td>Стоимость</td>
                                <td><input type="text" name="price" id="price" class="form-control" value="@Decimal.Round(Model.FirstOrDefault(x => x.id==1).price.GetValueOrDefault(),2)"></td>
                            </tr>
                            <tr>
                                <td>Количество:</td>
                                <td><input type="text" name="count" id="count" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).count"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button class="btn btn-primary" type="submit" onclick="sendPost('HDD')">Сохранить</button>
                    </div>
                </div>
            </section>
        </form>
    }

<script>
    $(document).ready(function () {
        $("#idManufacture").val(@Model.FirstOrDefault(x => x.id == 1).idbrand);
        $("#idRam").val(@Model.FirstOrDefault(x => x.id == 1).idtype);
    });
</script>

Diplom/Views/Credit/CreditPower.cshtml
@model List<Diplom.Models.ViewModel>


@{
    ViewBag.Title = "Запрос - Блок питания";
}

    @using (Ajax.BeginForm("CreditPower", "Credit", new AjaxOptions() { HttpMethod = "POST" }))
    {
        <form>
            <section style="margin-top:30px">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1>Введите данные (Блок питания)</h1>
                    </div>
                    @if (Model.FirstOrDefault(x => x.id == 1).uniqId != 0)
                    {
                        <input class="form-control invisible" name="idPower" value="@Model.FirstOrDefault(x => x.id == 1).uniqId" />
                    }
                    <div class="modal-body">
                        <table class="table table-condensed table-striped table-bordered">
                            <tr>
                                <td>Наименование:</td>
                                <td><input name="namePower" type="text" id="namePower" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).Name"></td>
                            </tr>
                            <tr>
                                <td>Производитель:</td>
                                <td>
                                    <select name="idManufacture" id="idManufacture" class="form-control">
                                        @foreach (var item in Model)
                                        {
                                            if (item.brand != null)
                                            {
                                                <option value="@item.id">@item.brand</option>
                                            }
                                        }
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td>Мощность</td>
                                <td><input type="text" name="cap" id="cap" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).cap"></td>
                            </tr>
                            <tr>
                                <td>Стоимость</td>
                                <td><input type="text" name="price" id="price" class="form-control" value="@Decimal.Round(Model.FirstOrDefault(x => x.id==1).price.GetValueOrDefault(),2)"></td>
                            </tr>
                            <tr>
                                <td>Количество:</td>
                                <td><input type="text" name="count" id="count" class="form-control" value="@Model.FirstOrDefault(x => x.id==1).count"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal">Закрыть</button>
                        <button class="btn btn-primary" type="submit" onclick="sendPost('Power')">Сохранить</button>
                    </div>
                </div>
            </section>
        </form>
    }

<script>
    $(document).ready(function () {
        $("#idManufacture").val(@Model.FirstOrDefault(x => x.id == 1).idbrand);
    });
</script>